on: [push]

jobs:
    hello-world-job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            - name: Hello world action step
              id: hello
              uses: mokhlesurr031/hello-action@v1
              with:
                who-to-greet: "Mahin the Boss"
            - name: Get the output time
              run: echo "The time was ${{ steps.hello.outputs.time }}"
              
              